# Header
menu:
  主页: /
  所有文章: /archives/
  随笔: /tags/
  友链: /links/

# SubNav
subnav:
  github: "https://github.com/icaife"
  weibo: "http://weibo.com/detectivecoder"
  rss: "#"
  facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.png

#你的头像
avatar: "http://icaifeimg.qiniudn.com/ava.jpg"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: true
#是否开启云标签
tagcloud: true
#百度统计
baidutongji: true
